#!/usr/bin/env sh

mkdir -p build/
yes "" | pdflatex --output-directory=build/ main
biber --input-directory=build/ main
yes "" | pdflatex --output-directory=build/ main
yes "" | pdflatex --output-directory=build/ main

zathura build/main.pdf
